name: Benchmark
on:
  - push
permissions:
  actions: read
  contents: read
jobs:
  benchmark:
    name: 🥇 Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install hyperfine
        run: sudo apt install hyperfine
      - name: Run benchmarks
        run: bun benchmark
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: benchmarks
          path: dist/benchmarks
