name: Test
on:
  push: {}
  pull_request: {}
jobs:
  narrow-tests:
    name: 🐜 Narrow tests
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: '18.3.0'
      - name: Install dependencies
        run: pnpm install
      - name: Run Vitest
        run: pnpm test-narrow

  wide-tests:
    name: 🐘 Wide tests
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: '18.3.0'
      - name: Install dependencies
        run: pnpm install
      - name: Run Playwright tests
        run: pnpm test-wide --reporter=html
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
