name: Test

on:
  - push

permissions:
  actions: read
  contents: read

jobs:
  test:
    strategy:
      matrix:
        test: ['jest', 'jest-ng', 'jest-swc', 'vitest', 'vitest-swc']
    name: ✅ Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile

      - run: bun benchmark ${{ matrix.test }}
