name: 🚀 Test & Deploy
on:
  push:

env:
  # Using Nx Cloud is safer
  NX_REJECT_UNKNOWN_LOCAL_CACHE: 0

jobs:
  test-and-deploy:
    name: 🚀 Test & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.ref_name }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Nx
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/nx
          key: ${{ runner.os }}-nx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-nx

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install

      - run: pnpm nx run-many --parallel=4 -t lint,test
      - run: pnpm nx affected --parallel=4 -t deploy
